### ISSUE TITLE
Switch from dabplus-odr-padenc@.service to odr-padenc@.service

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/dabplus-on-air-processing#2]
As discussed and decided during November, the [odr-padenc package](https://github.com/radiorabe/centos-rpm-odr-padenc) now uses its own systemd service unit template (which can also be used without the dabplus-on-air-processing. Switch to this one and adapt the path accordingly.

**Comment by hairmare** [comment]
The original [odr-padenc service file](https://github.com/radiorabe/dabplus-on-air-processing/blob/master/dabplus-odr-padenc%40.service) also had `Before=liquidsoap@dabplus-on-air-processing.service`. I'm not sure how I could solve this with just [`dabplus-on-air-processing.service`](https://github.com/radiorabe/dabplus-on-air-processing/blob/master/dabplus-on-air-processing.service) (which I don't plan on using since it's more pain than help anyway).

Any ideas? I'm not sure what to do because `liquidsoap@.service` is in a different package as well.

**Comment by paraenggu** [comment]
Maybe we should get rid of [<code>dabplus-on-air-processing.service</code>](https://github.com/radiorabe/dabplus-on-air-processing/blob/master/dabplus-on-air-processing.service) completely (as it only acts as a meta-service  anyway) and document (or install) an unit override for [<code>odr-padenc@dabplus-on-air-processing.service</code>](https://github.com/radiorabe/centos-rpm-odr-padenc/blob/master/odr-padenc%40.service) which specifies the appropriate start-up order (<code>Before=[liquidsoap@dabplus-on-air-processing.service](https://github.com/radiorabe/centos-rpm-liquidsoap/blob/master/liquidsoap%40.service)</code> and maybe also a <code>[RequiredBy=](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#WantedBy=)[liquidsoap@dabplus-on-air-processing.service](https://github.com/radiorabe/centos-rpm-liquidsoap/blob/master/liquidsoap%40.service)</code> directive). Or the other way round for the <code>[liquidsoap@dabplus-on-air-processing.service](https://github.com/radiorabe/centos-rpm-liquidsoap/blob/master/liquidsoap%40.service)</code> (with <code>After=[odr-padenc@dabplus-on-air-processing.service](https://github.com/radiorabe/centos-rpm-odr-padenc/blob/master/odr-padenc%40.service)</code> and <code>Requires=[odr-padenc@dabplus-on-air-processing.service](https://github.com/radiorabe/centos-rpm-odr-padenc/blob/master/odr-padenc%40.service)</code>).
